name: Build and Test
 
on:
  push:
    branches:    
    - main 
  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
    - name: Pull request auto merge enabler
      if: github.event_name == 'pull_request'
      uses: poad/github-pull-request-auto-merge-enable-action@v2
      with:
        pull_request_number: ${{ github.event.pull_request.number }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.event.repository.name }}
        owner: ${{ github.repository_owner }}
        merge_method: SQUASH

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        targets:
          - numpy-matplotlib-example
          - numpy-matplotlib-example

    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml

      - name: Use Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "${{ matrix.targets }}/.python-version"
        
      - name: run
        working-directory: ${{ matrix.targets }}
        run: uv run hello.py